export const CATEGORY_PRODUCTS_TYPES = {
  notebook: 'Notebook',
  tablet: 'Tablet',
  phone: 'Celular',
};

export const LOCAL_STORAGE_KEYS = {
  SELECTED_PRODUCT: 'ELETROCADO__PRODUCT__SELECT_PRODUCT',
  CART_PRODUCT: 'ELETROCADO__CART__CART_PRODUCT',
  ENVOY_PRODUCT: 'ELETROCADO__ENVOY__ENVOY_PRODUCT',
};
